"""
Copies the speech sources from the research repository into this service.

The bridge ships its own copy of three things: the text front-end (normaliser, G2P
engine, lexicon), the vendored Coqui TTS library and the vendored trainer package.
That is what lets a server run the service from one checkout. The research
repository stays the source of truth — training, dataset preparation, vocabulary
building and evaluation all use the same front-end, and the models are trained on
whatever phonemes it produces.

Run this after changing the pipeline in the research repository:

    python tools/sync_from_ml.py --ml-root ../voicelk_ml

and run it with --check in CI or before a release to prove the copy is still faithful:

    python tools/sync_from_ml.py --ml-root ../voicelk_ml --check

--check exits with status 1 when the copy differs from the research repository, so a
stale copy fails the build instead of quietly mispronouncing words in production.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

BRIDGE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BRIDGE_DIR))

from app.fingerprint import STAMP_FILENAME, file_digests, fingerprint  # noqa: E402

VENDOR_DIR = BRIDGE_DIR / "vendor"

# (source path inside the research repository, destination inside vendor/)
COMPONENTS: List[Tuple[str, str]] = [
    ("model_engine", "model_engine"),
    ("model_training/TTS", "TTS"),
    ("model_training/trainer", "trainer"),
]

IGNORED = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo", ".DS_Store")


def git_commit(repo: Path) -> str:
    """Short commit of the research checkout, when it is a git working copy."""
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.stdout.strip() if result.returncode == 0 else "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def copy_component(source: Path, destination: Path) -> int:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=IGNORED)
    return sum(1 for path in destination.rglob("*") if path.is_file())


def compare(source: Path, destination: Path) -> Dict[str, List[str]]:
    """Files that differ between the research repository and the bundled copy."""
    source_digests = file_digests(source)
    copy_digests = file_digests(destination)

    return {
        "missing": sorted(set(source_digests) - set(copy_digests)),
        "extra": sorted(set(copy_digests) - set(source_digests)),
        "changed": sorted(
            name
            for name, digest in source_digests.items()
            if name in copy_digests and copy_digests[name] != digest
        ),
    }


def write_stamp(ml_root: Path, files_copied: Dict[str, int]) -> dict:
    stamp = {
        "synced_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source_root": str(ml_root),
        "source_commit": git_commit(ml_root),
        "frontend_fingerprint": fingerprint(VENDOR_DIR / "model_engine"),
        "files_copied": files_copied,
        "note": (
            "Generated by the sync tool. The research repository is the source of truth "
            "for the text front-end; do not edit the bundled copy by hand."
        ),
    }
    (VENDOR_DIR / STAMP_FILENAME).write_text(
        json.dumps(stamp, indent=2) + "\n", encoding="utf-8"
    )
    return stamp


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync the speech sources from the research repository.")
    parser.add_argument(
        "--ml-root",
        default=str(BRIDGE_DIR.parent / "voicelk_ml"),
        help="Path to the research repository checkout.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report differences without copying anything; exits 1 when the copy is stale.",
    )
    args = parser.parse_args()

    ml_root = Path(args.ml_root).expanduser().resolve()
    if not ml_root.is_dir():
        print(f"Research repository not found at '{ml_root}'.")
        return 2

    missing = [name for name, _ in COMPONENTS if not (ml_root / name).is_dir()]
    if missing:
        print(f"'{ml_root}' does not look like the research repository. Missing: {', '.join(missing)}")
        return 2

    if args.check:
        stale = False
        for source_name, destination_name in COMPONENTS:
            differences = compare(ml_root / source_name, VENDOR_DIR / destination_name)
            problems = {kind: names for kind, names in differences.items() if names}
            if problems:
                stale = True
                print(f"\n{destination_name}: out of date")
                for kind, names in problems.items():
                    preview = ", ".join(names[:5]) + (" …" if len(names) > 5 else "")
                    print(f"  {kind} ({len(names)}): {preview}")
            else:
                print(f"{destination_name}: up to date")

        if stale:
            print("\nThe bundled copy differs from the research repository. Run the sync without --check.")
            return 1

        print("\nThe bundled copy matches the research repository.")
        return 0

    VENDOR_DIR.mkdir(parents=True, exist_ok=True)

    files_copied: Dict[str, int] = {}
    for source_name, destination_name in COMPONENTS:
        count = copy_component(ml_root / source_name, VENDOR_DIR / destination_name)
        files_copied[destination_name] = count
        print(f"{destination_name}: {count} file(s)")

    stamp = write_stamp(ml_root, files_copied)
    print(f"\nFront-end fingerprint: {stamp['frontend_fingerprint']}")
    print(f"Source commit        : {stamp['source_commit']}")
    print("Stamp written. Commit the vendor folder together with this change.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
